/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "use-controllable-state": {
    name: "use-controllable-state",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-layout-effect.tsx",
      type: "registry:hook",
    },{
      path: "src/registry/src/hooks/use-controllable-state.ts",
      type: "registry:hook",
    }],
  },
  "use-sound": {
    name: "use-sound",
    description: "Custom React hook to load and play a sound from a given URL using the Web Audio API.",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-sound.ts",
      type: "registry:hook",
    }],
  },
  "book-call": {
    name: "book-call",
    description: "A simple call-to-action button for booking meetings with a subtle hover animation.",
    type: "registry:component",
    files: [{
      path: "src/registry/book-call/book-call.tsx",
      type: "registry:component",
    }],
  },
  "book-call-block-01": {
    name: "book-call-block-01",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/book-call-demo.tsx",
      type: "registry:component",
    }],
  },
  "book-call-block-02": {
    name: "book-call-block-02",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/book-call-demo-02.tsx",
      type: "registry:component",
    }],
  },
  "book-call-demo": {
    name: "book-call-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/book-call-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/book-call-demo.tsx")),
  },
  "book-call-demo-02": {
    name: "book-call-demo-02",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/book-call-demo-02.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/book-call-demo-02.tsx")),
  },
}